---
- hosts: target
  name: "Prepare env"
  become: yes
  gather_facts: no
  tasks:
    - name: "setup IP on Ironic interface"
      raw: ifconfig {{ network_interface }} 192.168.10.2/24 up
    - name: "wait apt"
      raw: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 30;done
    - name: "apt update"
      raw: apt -y update
    - name: "install python"
      raw: apt -y install --no-install-recommends python

- hosts: target
  name: "Install Ironic on the local host."
  become: yes
  gather_facts: yes
  roles:
    - { role: bifrost-prep-for-install, when: skip_install is not defined }
    - bifrost-keystone-install
    - bifrost-horizon-install
    - bifrost-ironic-install
    - { role: bifrost-keystone-client-config, config_username: "{{ ironic.keystone.default_username }}", config_password: "{{ ironic.keystone.default_password }}", config_project_name: "baremetal", config_region_name: "{{ keystone.bootstrap.region_name }}", config_auth_url: "{{ keystone.bootstrap.public_url }}", user: "{{ ansible_env.SUDO_USER }}", when: enable_keystone is defined and enable_keystone | bool == true }
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
